import { Product } from "../type/product";

export const products: Product[] = [
    {
        id: 1,
        cat: 's',
        title: 'SHAWARMA I RULL',
        content: 'Agurk, chicken',
        price: 120,
        allergier: 'Allergier: gluten',
        img: './assets/shawarmarull.jpg',
    },
    {
        id: 2,
        cat: 's',
        title: 'SHAWARMA TALLARKEN',
        content: 'Agurk, chicken',
        price: 140,
        allergier: 'Allergier: gluten',
        img: './assets/shawrma-arabi.jpeg',
    },
    {
        id: 3,
        cat: 's',
        title: 'HUNGRY BIRDS ',
        content: 'Agurk, chicken',
        price: 165,
        allergier: 'Allergier: gluten',
        img: './assets/hungry-birds.png',
    },
    {
        id: 4,
        cat: 'c',
        title: 'CRISPY CHICKEN RULL',
        content: 'Agurk, chicken',
        price: 100,
        allergier: 'Allergier: gluten',
        img: './assets/cripsy-rull.png',
    },
    {
        id: 5,
        cat: 'c',
        title: 'CRISPY SNACK BOX',
        content: 'Agurk, chicken',
        price: 100,
        allergier: 'Allergier: gluten',
        img: './assets/crispy-snack-box.jpeg',
    },
    {
        id: 6,
        cat: 'c',
        title: 'CRIPSY BOX',
        content: 'Agurk, chicken',
        price: 100,
        allergier: 'Allergier: gluten',
        img: './assets/cripsy-box.jpg',
    },
    {
        id: 7,
        cat: 'c',
        title: 'CRIPSY BURGER',
        content: 'Agurk, chicken',
        price: 100,
        allergier: 'Allergier: gluten',
        img: './assets/crispy-burger.jpg',
    },
    {
        id: 8,
        cat: 'v',
        title: 'FALAFEL RULL',
        content: 'Agurk, chicken',
        price: 100,
        allergier: 'Allergier: gluten',
        img: './assets/falafel-rull.jpeg',
    },
];
